### ISSUE TITLE
Use of django.utils.importlib deprecated in django 1.9

### ISSUE THREAD

**Issue by lukeburden** [roverdotcom/django-inlinecss#20]
https://github.com/roverdotcom/django-inlinecss/blob/master/django_inlinecss/conf.py#L1

Throws a warning in Django 1.8, will result in an error in 1.9. Need to use python's native equivalent module "importlib".

**Comment by damacisaac** [comment]
+1

**Comment by Pavlov123** [comment]
Just made a pull request that resolves the issue.
