### ISSUE TITLE
I'm getting the error InvalidTemplateLibrary, when including django_inlinecss in my INSTALLED_APPS

### ISSUE THREAD

**Issue by juliancantillo** [roverdotcom/django-inlinecss#26]
I am using Django 1.9.5

InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_inlinecss.templatetags.inlinecss': cannot import name importlib

**Comment by dtrinchet** [comment]
Use this version instead -e git://github.com/roverdotcom/django-inlinecss.git@master#egg=django-inlinecss-master

**Comment by juliancantillo** [comment]
Thanks, I did this yesterday, I was going to close the issue, and inform my
experience. If someone else experience the same only have to use the last
version from github.

On Tue, May 3, 2016 at 7:25 AM Dannier Trinchet Almaguer <
notifications@github.com> wrote:

> Use this version instead -e git://
> github.com/roverdotcom/django-inlinecss.git@master#egg=django-inlinecss-master
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/roverdotcom/django-inlinecss/issues/26#issuecomment-216512079>
>
-- 

​
{
   "name"     : "Julian Cantillo",

  "title"    : "Web Developer",

  "location" : ["Cali, Colombia"],

  "twitter"  : ["@JulianCantillo <http://twitter.com/JulianCantillo>"],

  "website"  : ["juliancantillo.me <https://www.juliancantillo.me/>"],

}

**Comment by juliancantillo** [comment]
Install the library using:
```
pip install git+https://github.com/roverdotcom/django-inlinecss
```
